def bandeira_marrocos(t, x, y):
  t.penup()
  t.goto(x, y)
  t.pendown()
  t.color("red")
  t.begin_fill()
  t.forward(100)
  t.right(90)
  t.forward(60)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(60)
  t.right(90)
  t.end_fill()
  t.penup()
  t.goto(x + 40, y - 25)
  t.color('green')
  t.pendown()
  for i in range(5):
    t.forward(20)
    t.right(144)
  t.penup()


def bandeira_turquia(t, x, y):
  t.penup()
  t.goto(x, y)
  t.pendown()
  t.color("red")
  t.begin_fill()
  t.forward(100)
  t.right(90)
  t.forward(60)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(60)
  t.right(90)
  t.end_fill()
  t.penup()
  t.goto(x + 40, y - 40)
  t.color('white')
  t.begin_fill()
  t.circle(15)
  t.end_fill()
  t.penup()
  t.goto(x + 50, y - 40)
  t.color('red')
  t.begin_fill()
  t.circle(15)
  t.end_fill()
  t.penup()
  t.goto(x + 40, y - 20)
  t.color('white')
  t.pendown()
  for i in range(5):
    t.forward(20)
    t.right(144)


def estrelinha(t, x, y):
  t.penup()
  t.goto(x, y)
  t.color('white')
  t.pendown()
  for i in range(5):
    t.forward(10)
    t.right(144)


def bandeira_brasil(t, x, y):
  t.penup()
  t.goto(x, y)
  t.color('green')
  t.pendown()
  t.begin_fill()
  t.forward(200)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.forward(200)
  t.right(90)
  t.forward(100)
  t.right(90)
  t.end_fill()
  t.goto(0, 0)
  t.color('yellow')
  t.begin_fill()
  t.right(27)
  t.forward(12500**0.5)
  t.right(127)
  t.forward(12500**0.5)
  t.right(53)
  t.forward(12500**0.5)
  t.right(127)
  t.forward(12500**0.5)
  t.end_fill()

  t.goto(15, -77)
  t.color('blue')
  t.begin_fill()
  t.circle(35)
  t.end_fill()

  t.penup()
  t.goto(30, -35)
  t.color('white')
  t.pendown()
  t.begin_fill()
  t.right(15)
  t.bk(65)
  t.right(90)
  t.forward(10)
  t.lt(90)
  t.forward(65)
  t.lt(90)
  t.forward(10)
  t.end_fill()

  estrelinha(t, -10, -30)

  estrelinha(t, -10, -60)

  estrelinha(t, -20, -67)

  estrelinha(t, 0, -70)

  estrelinha(t, 10, -60)

  estrelinha(t, -10, -80)

  estrelinha(t, 17, -65)

  estrelinha(t, 8, -75)
